version: 2.1

orbs:
  saucectl: saucelabs/saucectl-run@dev:alpha

jobs:
  test_local:
    docker:
      - image: cimg/base:stable
    environment:
      SAUCE_USERNAME: $SAUCE_USERNAME
      SAUCE_ACCESS_KEY: $SAUCE_ACCESS_KEY
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - saucectl/saucectl-run:
          show-console-log: true
          config-file: ./sauce/config.yml
          region: us-west-1
  test_sauce:
    docker:
      - image: cimg/base:stable
    environment:
      SAUCE_USERNAME: $SAUCE_USERNAME
      SAUCE_ACCESS_KEY: $SAUCE_ACCESS_KEY
    steps:
      - checkout
      - saucectl/saucectl-run:
          show-console-log: true
          config-file: ./.sauce/config.yml
          region: us-west-1
          testing-environment: sauce

workflows:
  test_local_and_remote:
    jobs:
      - test_local
      - test_sauce:
          requires:
            - test_local
