version: 2.1

orbs:
  saucectl: saucelabs/saucectl-run@dev:alpha

jobs:
  test_local:
    steps:
      - checkout
      - saucectl/saucectl-run:
          show-console-log: true
          sauce-username: $SAUCE_USERNAME
          sauce-access-key: $SAUCE_ACCESS_KEY
          config-file: ./sauce/config.yml
          region: us-west-1
  test_sauce:
    steps:
      - checkout
      - saucectl/saucectl-run:
          show-console-log: true
          sauce-username: $SAUCE_USERNAME
          sauce-access-key: $SAUCE_ACCESS_KEY
          config-file: ./sauce/config.yml
          region: us-west-1
          testing-environment: sauce

workflows:
  test_local_and_remote:
    jobs:
      - test_local
      - test_sauce:
          requires:
            - test_local
