version: 2.1

orbs:
  saucectl: saucelabs/saucectl-run@dev:alpha

workflows:
  test_local_and_remote:
    jobs:
      - saucectl/saucectl-run:
          show-console-log: true
          config-file: ./.sauce/config.yml
          region: us-west-1
      - saucectl/saucectl-run:
          show-console-log: true
          config-file: ./.sauce/config.yml
          region: us-west-1
          testing-environment: sauce
