version: 2.1

orbs:
  saucectl: saucelabs/saucectl-run@dev:alpha

workflows:
  test:
    jobs:
      - saucectl/run:
          show-console-log: true
          sauce-username: $SAUCE_USERNAME
          sauce-access-key: $SAUCE_ACCESS_KEY
          config-file: ./sauce/config.yml
          region: us-west-1
      - saucectl/run:
          show-console-log: true
          sauce-username: $SAUCE_USERNAME
          sauce-access-key: $SAUCE_ACCESS_KEY
          config-file: ./sauce/config.yml
          region: us-west-1
          testing-environment: sauce
