version: 2.1

orbs:
  saucectl: saucelabs/saucectl-run@dev:alpha

jobs:
  test_locally:
    docker:
      - image: cimg/base:stable
    steps:
      - saucectl/run:
          show-console-log: true
          sauce-username: $SAUCE_USERNAME
          sauce-access-key: $SAUCE_ACCESS_KEY
          config-file: ./sauce/config.yml
          region: us-west-1

  test_remotely:
    docker:
      - image: cimg/base:stable
    steps:
      - saucectl/run:
          show-console-log: true
          sauce-username: $SAUCE_USERNAME
          sauce-access-key: $SAUCE_ACCESS_KEY
          config-file: ./sauce/config.yml
          region: us-west-1
          testing-environment: sauce

workflows:
  test:
    jobs:
      - test_locally
      - test_remotely
